artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion

data_validation:
  root_dir: artifacts/data_validation
  STATUS_FILE: artifacts/data_validation/status.txt
  unzip_data_dir: artifacts/data_ingestion/unzip
  all_required_files:
    - train.csv
    - test.csv


